spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gregorysouzagr@gmail.com
    password:
    protocol: smtp
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  thymeleaf:
    enable: true

envio:
  email:
    remetente: gregorysouzagr@gmail.com
    nomeRemetente: 'Gregory'

server:
  port: 8082